// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID    string
	Title string
}

type Solved struct {
	UserID     int64
	Username   pgtype.Text
	ExerciseID string
	Title      pgtype.Text
}

type Submission struct {
	UserID     int64
	ExerciseID string
	Code       pgtype.Text
	Output     pgtype.Text
}

type User struct {
	ID       int64
	Username string
	Password string
	Token    string
	Approved bool
}
