// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Exercise struct {
	ID    string
	Title string
}

type Submission struct {
	UserID     int64
	ExerciseID string
	Code       string
	Output     string
	Evaluation string
	Solved     int32
}

type User struct {
	ID       int64
	Username string
	Password string
	Token    string
	Approved bool
}
