// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExercise = `-- name: CreateExercise :exec
INSERT INTO exercises (
    id, title
) VALUES (
  $1, $2
) ON CONFLICT DO NOTHING
`

type CreateExerciseParams struct {
	ID    string
	Title string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) error {
	_, err := q.db.Exec(ctx, createExercise, arg.ID, arg.Title)
	return err
}

const createSubmission = `-- name: CreateSubmission :exec
INSERT INTO submissions (
    user_id, exercise_id, code, output, evaluation, solved
) VALUES (
     $1, $2, $3, $4, $5, $6
) ON CONFLICT (user_id, exercise_id) DO UPDATE
SET
    code = EXCLUDED.code,
    output = EXCLUDED.output,
    evaluation = EXCLUDED.evaluation,
    solved = EXCLUDED.solved,
    attempts = submissions.attempts + 1
`

type CreateSubmissionParams struct {
	UserID     int64
	ExerciseID string
	Code       string
	Output     string
	Evaluation string
	Solved     int32
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) error {
	_, err := q.db.Exec(ctx, createSubmission,
		arg.UserID,
		arg.ExerciseID,
		arg.Code,
		arg.Output,
		arg.Evaluation,
		arg.Solved,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
  username, password, token, approved
) VALUES (
  $1, $2, $3, $4
) ON CONFLICT DO NOTHING
`

type CreateUserParams struct {
	Username string
	Password string
	Token    string
	Approved bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Token,
		arg.Approved,
	)
	return err
}

const getExercises = `-- name: GetExercises :many
SELECT id, title FROM exercises
ORDER BY id ASC
`

func (q *Queries) GetExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, getExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatus = `-- name: GetStatus :many
SELECT
    u.id AS user_id,
    COALESCE(s.solved, 0) AS solved,
    s.attempts
FROM users u
    LEFT JOIN submissions s
    ON s.user_id = u.id
    AND s.exercise_id = $1
ORDER BY u.id ASC
`

type GetStatusRow struct {
	UserID   int64
	Solved   int32
	Attempts pgtype.Int4
}

func (q *Queries) GetStatus(ctx context.Context, exerciseID string) ([]GetStatusRow, error) {
	rows, err := q.db.Query(ctx, getStatus, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatusRow
	for rows.Next() {
		var i GetStatusRow
		if err := rows.Scan(&i.UserID, &i.Solved, &i.Attempts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmission = `-- name: GetSubmission :one
SELECT user_id, exercise_id, code, output, evaluation, solved, attempts FROM submissions
WHERE user_id = $1 AND exercise_id = $2
`

type GetSubmissionParams struct {
	UserID     int64
	ExerciseID string
}

func (q *Queries) GetSubmission(ctx context.Context, arg GetSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmission, arg.UserID, arg.ExerciseID)
	var i Submission
	err := row.Scan(
		&i.UserID,
		&i.ExerciseID,
		&i.Code,
		&i.Output,
		&i.Evaluation,
		&i.Solved,
		&i.Attempts,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password, token, approved FROM users
WHERE username = $1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Token,
		&i.Approved,
	)
	return i, err
}

const getUserFromId = `-- name: GetUserFromId :one
SELECT id, username, password, token, approved FROM users
WHERE id = $1
`

func (q *Queries) GetUserFromId(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserFromId, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Token,
		&i.Approved,
	)
	return i, err
}

const getUserFromToken = `-- name: GetUserFromToken :one
SELECT id, username, password, token, approved FROM users
WHERE token = $1
`

func (q *Queries) GetUserFromToken(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRow(ctx, getUserFromToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Token,
		&i.Approved,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, password, token, approved FROM users
WHERE approved = true
ORDER BY id ASC
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.Token,
			&i.Approved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
